// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaK-1Qpe0bAyO1SOfMaHuxLiuc9V8uhKM',
    appId: '1:931289080351:web:b6f5408839c00f56b7ab2a',
    messagingSenderId: '931289080351',
    projectId: 'cam-sat-klima',
    authDomain: 'cam-sat-klima.firebaseapp.com',
    storageBucket: 'cam-sat-klima.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsxquIeN5BkeJ8W9-T7-26PNXsxYYv06g',
    appId: '1:931289080351:android:6f7787b27d4bde3cb7ab2a',
    messagingSenderId: '931289080351',
    projectId: 'cam-sat-klima',
    storageBucket: 'cam-sat-klima.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgEZBppQWS2fkvzr0qy0QgWT9eI4CfGbk',
    appId: '1:931289080351:ios:c972329ff4dff6a7b7ab2a',
    messagingSenderId: '931289080351',
    projectId: 'cam-sat-klima',
    storageBucket: 'cam-sat-klima.firebasestorage.app',
    iosBundleId: 'pl.camsat.klima',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgEZBppQWS2fkvzr0qy0QgWT9eI4CfGbk',
    appId: '1:931289080351:ios:d10861a6cde1761bb7ab2a',
    messagingSenderId: '931289080351',
    projectId: 'cam-sat-klima',
    storageBucket: 'cam-sat-klima.firebasestorage.app',
    iosBundleId: 'com.example.klimaTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaK-1Qpe0bAyO1SOfMaHuxLiuc9V8uhKM',
    appId: '1:931289080351:web:b6f5408839c00f56b7ab2a',
    messagingSenderId: '931289080351',
    projectId: 'cam-sat-klima',
    authDomain: 'cam-sat-klima.firebaseapp.com',
    storageBucket: 'cam-sat-klima.firebasestorage.app',
  );
}
